services:
    user_repository:
        class: App\Repository\UserRepository
        arguments: ["@doctrine.orm.entity_manager"]

    group_repository:
      class: App\Repository\GroupRepository
      arguments: ["@doctrine.orm.entity_manager"]